ALTER TABLE appointment
    ALTER COLUMN created_at DROP NOT NULL;

ALTER TABLE doctor
    ALTER COLUMN created_at DROP NOT NULL;

ALTER TABLE patient
    ALTER COLUMN created_at DROP NOT NULL;

ALTER TABLE appointment
ALTER
COLUMN note TYPE VARCHAR(255) USING (note::VARCHAR(255));

ALTER TABLE appointment
ALTER
COLUMN status TYPE VARCHAR(255) USING (status::VARCHAR(255));

ALTER TABLE appointment
    ALTER COLUMN updated_at DROP NOT NULL;

ALTER TABLE doctor
    ALTER COLUMN updated_at DROP NOT NULL;

ALTER TABLE patient
    ALTER COLUMN updated_at DROP NOT NULL;
CREATE TABLE appointment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    doctor_id  BIGINT                                  NOT NULL,
    patient_id BIGINT                                  NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    note       VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_appointment PRIMARY KEY (id)
);

CREATE TABLE doctor
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(100)                            NOT NULL,
    specialty  VARCHAR(100)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_doctor PRIMARY KEY (id)
);

CREATE TABLE patient
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name  VARCHAR(150)                            NOT NULL,
    email      VARCHAR(150)                            NOT NULL,
    phone      VARCHAR(50),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_patient PRIMARY KEY (id)
);

ALTER TABLE appointment
    ADD CONSTRAINT FK_APPOINTMENT_ON_DOCTOR FOREIGN KEY (doctor_id) REFERENCES doctor (id);

ALTER TABLE appointment
    ADD CONSTRAINT FK_APPOINTMENT_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patient (id);